---
title: "ESM 204 Homework 4"
author: "Jordan Faires and Evan Heberlein"
date: "5/21/2020"
output: html_document
---

1. Plots 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

```{r}

# Setting up variables and functions

# Temperature is increasing over time - temp at time t equals min of (tT / 100, T). It rises until T = 100 and flattens out after that. If we know t and T, you can plug in to the equation. t = years from now, T = BAU temperature increase at year 100.

# Save variables to make manipulation easier

# Year
t <- 200

# BAU temp increase at year 100
T <- 4.4

# Other paramaters
B <- 0.05
g <- 0.01
d <- 0.005
n <- 0.5

# Functions 

# Temperature in year T relative to temp at time 0

temp = function(t,T)
{
  out = pmin(t*T/100,T)
  return(out)
  T = 4
  t = 100
}

temp(t, T)

# Economic Activity - Activity reduces with heat over time. Fraction of economic activity retained in a year if tempt is r(t):

activity = function(B, temp)
{
  out = exp(-B*(temp^2))
  return(out)
}

activity(B, temp = temp(t, T))

# Consumption - economic activity growing over time at rate g but reduced by K. total consumption at time t is: 

consumption = function(activity, g, t)
{
  out = activity*(exp(g*t))
  return(out)
}

consumption(g, t, activity = activity(B, temp = temp(t, T))) 

# Utility - society's utility from consumption 

utility = function(consumption, n)
{
  out = ((consumption^(1-n))/(1-n))
  return(out)
}

utility(n, consumption = (consumption(g, t, activity = activity(B, temp = temp(t, T)))))

# Discount rate given by Ramsey Rule 

discount = function(d, n, g)
{
  out = d + (n*g)
  return(out)
}

r <- discount(d, n, g)


```

```{r, include = FALSE}

# Plotting temperature 

years <- data.frame(
  year = seq(from = 0, to = 200, by = 1))
temp_time <- years %>%
  mutate(none = temp(t = year, T = 0),
         moderate = temp(t = year, T = 2),
         extreme = temp(t = year, T = 8))

colors <- c("Extreme (T = 8)" = "red3", "Moderate (T = 2)" = "seagreen", "None" = "dodgerblue")

```

a. Plot temperature over time for no climate change, moderate climate change and extreme climate change. 
```{r}
ggplot(temp_time, aes(x = year)) +
  geom_point(aes(y = moderate, color = "Moderate (T = 2)")) + 
  geom_point(aes(y = extreme, color = "Extreme (T = 8)")) +
  geom_point(aes(y = none, color = "None")) +
  theme_minimal() + 
  labs(x = "Year",
       y = "Temperature Increase Relative to Year Zero",
       title = "Temperature Over Time Under Multiple Climate Scenarios",
       fill = "") + 
    scale_colour_discrete("Climate Change Scenario")
```

```{r, include = FALSE}

#Plotting Consumption

#Calculating activity (in order to be able to calculate consumption)

activity_time <- temp_time %>%
  mutate(act_none = activity(B = .05 , temp = none),
         act_moderate = activity(B = .05 , temp = moderate),
         act_extreme = activity(B = .05 , temp = extreme))

#Calculating consumption

consumption_time <- activity_time %>% 
    mutate(con_none = consumption(activity = act_none, g = .01, t = year),
         con_moderate = consumption(activity = act_moderate, g = .01, t = year),
         con_extreme = consumption(activity = act_extreme, g = .01, t = year))
  
#Plot activity 

ggplot(consumption_time, aes(x = year)) +
  geom_point(aes(y = act_none, color = "None")) + 
  geom_point(aes(y = act_moderate, color = "Moderate (T = 2)")) +
  geom_point(aes(y = act_extreme, color = "Extreme (T = 8)")) +
  theme_minimal() + 
  labs(x = "Year",
       y = "activity",
       title = "activity Over Time",
       fill = "") 

``` 

b. Plot consumption over time for no climate change, moderate climate change and extreme climate change. 
```{r}
#Plot consumption 

ggplot(consumption_time, aes(x = year)) +
  geom_point(aes(y = con_none, color = "None")) + 
  geom_point(aes(y = con_moderate, color = "Moderate (T = 2)" )) +
  geom_point(aes(y = con_extreme, color = "Extreme (T = 8)")) +
  theme_minimal() + 
  labs(x = "Year",
       y = "Consumption",
       title = "Economic Activity (Consumption) Over Time",
       fill = "") +
    scale_colour_discrete("Climate Change Scenario")
```

c. Plot undiscounted utility over time for for no climate change, moderate climate change and extreme climate change. 

```{r}

#Plotting utility over time 

utility_time <- consumption_time %>% 
    mutate(util_none = utility(consumption = con_none, n = 0.5),
         util_moderate = utility(consumption = con_moderate, n = 0.5),
         util_extreme = utility(consumption = con_extreme, n = 0.5))

ggplot(utility_time, aes(x = year)) +
  geom_point(aes(y = util_none, color = "None")) + 
  geom_point(aes(y = util_moderate, color = "Moderate (T = 2)" )) +
  geom_point(aes(y = util_extreme, color = "Extreme (T = 8)")) +
  theme_minimal() + 
  labs(x = "Year",
       y = "Utility",
       title = "Undiscounted Utility Over Time",
       fill = "")  +
  scale_colour_discrete("Climate Change Scenario")

```




```{r}
# 2.a

U_disc = function(utility, r, t) {
  out = (utility/(1+r)^t)
  return(out)
}

y <- seq(0, 200, 1)

U_4.4_disc <- sum(U_disc(r, t = y, 
           utility = 
             utility(n, consumption = (consumption(g, t = y, activity = activity(B, temp = temp(t = y, T)))))))

U_4.4_indiv <- U_disc(r, t = y, 
            utility = 
              utility(n, consumption = (consumption(g, t = y, activity = activity(B, temp = temp(t = y, T))))))

U_0_disc <- sum(U_disc(r, t = y, 
           utility = 
             utility(n, consumption = (consumption(g, t = y, activity = activity(B, temp = temp(t = y, 0)))))))

U_0_indiv <- U_disc(r, t = y, 
            utility = 
              utility(n, consumption = (consumption(g, t = y, activity = activity(B, temp = temp(t = y, 0))))))

L <- (1 - (U_4.4_disc/U_0_disc))*100

# Example NPV fxn: NPV(cf0=100,cf=50,times=3,i=.05)

# 2.b
# Sensitivity to temp change (4.4 pathway only)

U_4.4_sens_T <- sum(U_disc(r, t = y, 
           utility = 
             utility(n, consumption = (consumption(g, t = y, activity = activity(B, temp = temp(t = y, T = 
                                                                                                  (T*1.1)
                                                                                                )))))))

L_sens_T <- ((L - 
                        ((1 - (U_4.4_sens_T/U_0_disc))*100) # Finding new L w/ 10% change in T
                  )/L)*100

# Sensitivity to g (economic growth rate)

U_4.4_sens_g <- sum(U_disc(r, t = y, 
           utility = 
             utility(n, consumption = (consumption(
               g = (1.1*g)
               , t = y, activity = activity(B, temp = temp(t = y, T)))))))

U_0_sens_g <- sum(U_disc(r, t = y, 
           utility = 
             utility(n, consumption = (consumption(
               g = (1.1*g)
               , t = y, activity = activity(B, temp = temp(t = y, 0)))))))

L_sens_g <- ((L - 
                        ((1 - (U_4.4_sens_g/U_0_sens_g))*100)
                  )/L)*100

# Sensitivity to n (growth coefficient?)

U_4.4_sens_n <- sum(U_disc(r, t = y, 
           utility = 
             utility(
               n = (1.1*n)
               , consumption = (consumption(g, t = y, activity = activity(B, temp = temp(t = y, T)))))))

U_0_sens_n <- sum(U_disc(r, t = y, 
           utility = 
             utility(
               n = (1.1*n)
               , consumption = (consumption(g, t = y, activity = activity(B, temp = temp(t = y, 0)))))))

L_sens_n <- ((L - 
                        ((1 - (U_4.4_sens_n/U_0_sens_n))*100)
                  )/L)*100
  
# Sensitivity to B (temp coefficient?)

U_4.4_sens_B <- sum(U_disc(r, t = y, 
           utility = 
             utility(n, consumption = (consumption(g, t = y, activity = activity(
               B=(1.1*B)
               , temp = temp(t = y, T)))))))

U_0_sens_B <- sum(U_disc(r, t = y, 
           utility = 
             utility(n, consumption = (consumption(g, t = y, activity = activity(
               B=(1.1*B)
               , temp = temp(t = y, 0)))))))

L_sens_B <- ((L - 
                        ((1 - (U_4.4_sens_B/U_0_sens_B))*100)
                  )/L)*100


```

